name: 'Release'
description: 'Version and publish packages using NX release'

runs:
  using: 'composite'
  steps:
    - name: Configure git
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Run NX release version
      shell: bash
      run: npx nx release version --verbose

    - name: Rebuild packages with new versions
      shell: bash
      run: npx nx run-many -t build --skipNxCache

    - name: Push changes and tags
      shell: bash
      run: |
        git push
        git push --tags

    - name: Verify built files
      shell: bash
      run: |
        echo "Verifying built files..."
        ls -la dist/packages/*/index.js || (echo "Built files missing!" && exit 1)
        # Double-check that we're publishing from dist directories
        echo "Checking package.json files in dist..."
        for pkg in dist/packages/*/package.json; do
          echo "=== $pkg ==="
          cat "$pkg" | grep -E '"name"|"main"|"types"'
        done

    - name: Run NX release publish
      shell: bash
      run: npx nx release publish
      env:
        NPM_CONFIG_PROVENANCE: true
        NPM_CONFIG_LEGACY_PEER_DEPS: false

    - name: Tag last-release
      shell: bash
      run: |
        git tag -f last-release
        git push origin last-release --force
        # push nx created tags
        git tag -l
        git push origin --tags
